// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdxlVnSI5Ej9XfCVKR7tVYjdKKmytztN4',
    appId: '1:601839079914:web:5ff59bd126d5d467d76293',
    messagingSenderId: '601839079914',
    projectId: 'quote-firebase-22c2f',
    authDomain: 'quote-firebase-22c2f.firebaseapp.com',
    storageBucket: 'quote-firebase-22c2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIe8HzYjpB7431CykmZvkT6AWkQm-UfVQ',
    appId: '1:601839079914:android:f40a9b27fb252275d76293',
    messagingSenderId: '601839079914',
    projectId: 'quote-firebase-22c2f',
    storageBucket: 'quote-firebase-22c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA147cVA9psBbBm4PyCuJcmpX56b13JL_E',
    appId: '1:601839079914:ios:7c61f2257eb6a1b0d76293',
    messagingSenderId: '601839079914',
    projectId: 'quote-firebase-22c2f',
    storageBucket: 'quote-firebase-22c2f.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA147cVA9psBbBm4PyCuJcmpX56b13JL_E',
    appId: '1:601839079914:ios:7c61f2257eb6a1b0d76293',
    messagingSenderId: '601839079914',
    projectId: 'quote-firebase-22c2f',
    storageBucket: 'quote-firebase-22c2f.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdxlVnSI5Ej9XfCVKR7tVYjdKKmytztN4',
    appId: '1:601839079914:web:7df28d7fa87f5312d76293',
    messagingSenderId: '601839079914',
    projectId: 'quote-firebase-22c2f',
    authDomain: 'quote-firebase-22c2f.firebaseapp.com',
    storageBucket: 'quote-firebase-22c2f.firebasestorage.app',
  );
}
